config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :students
  # resources :exams, only: [:index]
  # resources :courses
  # resources :grades, only: [:index]
  # resources :students, only: [:index]
  resources :courses do
    resources :exams, only: [:index, :new, :create]
    resources :students
  end

  resources :exams, only: [:show, :edit, :update, :destroy] do
    resources :grades
  end
  root "courses#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :student
  belongs_to :exam
  belongs_to :course

  # Validations
  validates :grade,
            presence: true,
            numericality: { greater_than_or_equal_to: 0}

  # uniqueness of index (exam, student)
  validates :exam,
            uniqueness: { scope: :student }
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @exam = Exam.find(params[:exam_id])
    @grades = @exam.grades
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @exam = Exam.find(params[:exam_id])
    @grade = Grade.new
    @course = @exam.course
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create

    @grade = Grade.new(grade_params)
    @exam = Exam.find(params[:exam_id])
    @grade.exam = @exam
    @grade.course = @exam.course
    @students = @grade.course.students
    
    respond_to do |format|
      if @grade.save
        format.html { redirect_to exam_grades_path(@grade.exam), notice: 'La nota fue creada exitosamente.' }
        format.json { render :show, status: :created, location: @grade }
      else
        
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to exam_grades_path(@grade.exam), notice: 'La nota se actualizo correctamente.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to exam_grades_path(@exam), notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
      @exam = Exam.find(params[:exam_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      #      params.fetch(:grade, {})
      params.require(:grade).permit(:grade, :course, :student_id, :exam)
    end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.erb
<%= simple_form_for([@exam, @grade]) do |form| %>
  <% if grade.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p> <strong> numero de errores: <%= grade.errors.count %></strong></p>

      
      <% grade.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <% if ! @grade.persisted? %>
  <%= form.association :student,
      collection: exam.students_without_grades,
      prompt: "Elija un estudiante" %>
  <% end %>
     


  
    <%= form.input :grade,
        label: 'nota' %>
  
  
  <div class="actions">
    <%= form.submit @grade.persisted? ? 'Modificar' : 'Crear',
        class: 'btn btn-success' %>

    <%= link_to 'Cancelar',
        exam_grades_path(@exam),
        class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/grades/edit.html.erb
<h1> Editando la nota: </h1>

<p> <strong>Estudiante:</strong> <%= @grade.student %></p>
  
<p> <strong>Examen: </strong> <%= @exam %></p>

<p> <strong>Cursada: </strong> <%= @exam.course%>

<%= render 'form', grade: @grade %>

<%# <%= link_to 'Show', @grade %> |
<%# <%= link_to 'Back', grades_path %>

app/views/grades/index.html.erb
<%= link_to 'Estudiantes',
    course_students_path(@exam.course),
    class: 'btn btn-primary' %>

<%= link_to 'Evaluaciones',
    course_exams_path(@exam.course),
    class: 'btn btn-primary' %>
<%= link_to 'Curso',
    course_path(@exam.course),
    class: 'btn btn-primary' %>

<h1>Notas del examen <%= @exam %> del <%= @exam.course %></h1>

<% if @grades.any? %>
<table class="table table-condensed">
  <thead>
    
    <tr>
      <th class="">
        Estudiante
      </th>
      <th class="text-center">
        Nota
      </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grades.each do |grade| %>
    
    <tr>
      <td> <%= grade.student %> </td>
      <td class="text-center"> <%= grade.grade %> </td>
      <td>
        <%= link_to 'Editar',
            edit_exam_grade_path(grade.exam, grade),
            class: 'btn btn-primary' %>
      </td>
      <td><%= link_to 'Borrar',
              exam_grade_path(grade.exam,grade),
              method: :delete,
              class: 'btn btn-danger',
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<h3> Aun no hay notas cargadas para este examen </h3>
<% end %>
<%= link_to 'Crear nota',
   new_exam_grade_path(@exam),
   class: 'btn btn-success' %>

app/views/grades/new.html.erb
<h1>Crear Nota</h1>

<p> <strong> Examen : </strong>  <%= @exam %> </p>
<p> <strong> Cursada: </strong> <%= @exam.course %></p>

<%= render 'form', { grade: @grade, students: @students, exam: @exam } %>

app/views/grades/show.html.erb
<h1> Notas del examen <%= @exam %> </h1>

<table class="table table-stripped">
  <thead>
    <tr>
      <td>
        Estudiante
      </td>
      <td>
        Nota
      </td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
      </td>
    </tr>
  </tbody>
</table>

  
<%= link_to 'Edit', edit_exam_grade_path(@grade) %> |
<%= link_to 'Back', exam_grades_path(@exam) %>